# overlays/dev/kustomization.yaml
bases:
  - ../../base  # Reference the base configuration

helmCharts:
  - name: my-app
    repo: file://../../base/helm-chart  # Path to Helm chart in the base directory
    valuesFile: overlays/dev/values-dev.yaml  # Dev-specific values.yaml
