# overlays/dev/kustomization.yaml
resources:
- ../../base  # Reference the base configuration

helmCharts:
  - name: my-app
    repo: file://../../base/helmchart  # Path to Helm chart in the base directory
    valuesFile: overlays/dev/values.yaml  # Dev-specific values.yaml
