apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ee:latest  # Change to gitlab-ce if you prefer
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
           - name: GITLAB_OMNIBUS_CONFIG
             value: |
               external_url 'http://gitlab.example.com'  # Replace with your domain
