apiVersion: apps/v1
kind: Deployment
metadata:
 name: example-namespace-deployment
 namespace: example-namespace
spec:
 replicas: 1
 selector:
   matchLabels:
     app: example-namespace-app
 template:
   metadata:
     labels:
       app: example-namespace-app
   spec:
     containers:
     - name: nginx
       image: nginx:latest