apiVersion:kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: "https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd"  # Reference the public Helm chart repo
helmCharts:
 - name: argo-cd
   version: "7.7.0"
   repo:https://github.com/argoproj/argo-helm
 # Specify the Helm chart repository
   chart: argo-cd
   releaseName: argo-cd
   namespace: argo-cd
   valuesFile: values.yaml