name: Deploy to GKE
on:
 push:
   branches:
     - k8s
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Authenticate to Google Cloud
       uses: google-github-actions/auth@v1
       with:
         credentials_json: '${{ secrets.GCP_ACCESS_KEY }}'
     - name: Configure kubectl for GKE
       run: |
         gcloud container clusters get-credentials YOUR_CLUSTER_NAME --zone YOUR_CLUSTER_ZONE --project YOUR_PROJECT_ID
     - name: Deploy to GKE
       run: |
         kubectl apply -f namespace.yaml
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml

  
