name: Deploy to Kubernetes

on:
  push:
    branches:
      - k8s  # Change to your default branch if needed

jobs:
  deploy_cluster_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure Kubernetes context for Cluster 1
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_CLUSTER_1 }}
        run: |
          echo "$KUBECONFIG" | base64 --decode > $HOME/.kube/config
          kubectl config use-context gke_mlconsole-poc_us-central1_gitlab

      - name: Deploy to Cluster 1
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

  
